apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iceberg-ledger-pvc
  namespace: iceberg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
